//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web10
{
    using System;
    using System.Collections.Generic;
    
    public partial class studinfo
    {
        public string studno { get; set; }
        public string studname { get; set; }
        public string studsex { get; set; }
        public string email { get; set; }
    }
}
